<template>
	<q-page>
		<q-list>
			<q-item-label header>Security</q-item-label>
			<q-item clickable v-ripple>
				<q-item-section>
					<q-item-label>Password</q-item-label>
					<q-item-label caption>
						Change your account password to keep your account secure.
					</q-item-label>
				</q-item-section>
				<q-item-section side top>
					<q-btn @click="openChangePassword" push color="primary" text-color="dark" unelevated
						label="Change" />
				</q-item-section>
			</q-item>
			<q-separator spaced />
			<q-item-label header>Multi-factor authentication</q-item-label>
			<q-item tag="label" v-ripple>
				<q-item-section>
					<q-item-label>Authentication app</q-item-label>
					<q-item-label caption>Use a time-based one-time code generated by an authenticator
						app.</q-item-label>
				</q-item-section>
				<q-item-section side top>
					<q-toggle color="primary" v-model="isTwoFactorAuthEnabled"
						@update:model-value="openTurnOnTwoFactorAuth" />
				</q-item-section>
			</q-item>
		</q-list>
	</q-page>
</template>

<script setup lang="ts">
import { useQuasar } from 'quasar';
import ChangePassword from 'src/components/ChangePassword.vue';
import TurnOnTwoFactorAuth from 'src/components/TurnOnTwoFactorAuth.vue';
import { useAuthStore } from 'src/stores/auth-store';
import { ref } from 'vue';

const $q = useQuasar();
const authStore = useAuthStore();

const isTwoFactorAuthEnabled = ref(authStore.user!.isTwoFactorAuthEnabled);

const openChangePassword = () => {
	$q.dialog({
		component: ChangePassword,
		componentProps: {
			persistent: true,
		},
	});
};

const openTurnOnTwoFactorAuth = async (isActive: boolean) => {
	if (isActive) {
		$q.dialog({
			component: TurnOnTwoFactorAuth,
			componentProps: {
				persistent: true,
			},
		})
			.onOk((enabled: boolean) => {
				isTwoFactorAuthEnabled.value = enabled;
			})
			.onCancel(() => {
				isTwoFactorAuthEnabled.value = false;
			})
			.onDismiss(() => {
				isTwoFactorAuthEnabled.value = authStore.user!.isTwoFactorAuthEnabled;
			});
	} else {
		try {
			await authStore.turnOffTwoFactorAuth();
			$q.notify({
				type: 'positive',
				message: 'Two-factor authentication has been successfully disabled.',
			});
		} catch (error) {
			isTwoFactorAuthEnabled.value = true;
			$q.notify({
				type: 'negative',
				message: (error as Error).message,
			});
		}
	}
};
</script>
